### ISSUE TITLE
i can't

### ISSUE THREAD

**Issue by rikutatarin** [Necrownyx/Twitch-Account-Toolbox#11]
when i type "python main.py" on cmd, it says;

Microsoft Windows [Version 10.0.19045.2604]
(c) Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\Umut>cd C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main

C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main>python main.py
C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main\main.py:26: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  profile = webdriver.FirefoxProfile()
[WDM] - Downloading: 16.9kB [00:00, ?B/s]
C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main\main.py:28: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(firefox_profile=profile, executable_path=GeckoDriverManager().install())
C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main\main.py:28: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
  driver = webdriver.Firefox(firefox_profile=profile, executable_path=GeckoDriverManager().install())
Traceback (most recent call last):
  File "C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main\main.py", line 140, in <module>
    start()
  File "C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main\main.py", line 28, in start
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=GeckoDriverManager().install())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Umut\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Umut\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Umut\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Umut\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Umut\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

C:\Users\Umut\Downloads\Compressed\Twitch-Account-Toolbox-main\Twitch-Account-Toolbox-main>

**Comment by Necrownyx** [comment]
you might be missing the GeckoDriverManager package.
it isn't currently in the requirements file as it is a fairly recent additition to the project
try intalling it and trying again
